# Utilise une image Python légère
FROM python:3.11-slim

# Installer les dépendances système (Tesseract et Poppler)
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    poppler-utils \
    libgl1 \
    && apt-get clean

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY requirements.txt .

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code
COPY . .

# Exposer le port (Render utilise $PORT)
ENV PORT=10000
EXPOSE 10000

# Commande de lancement
CMD uvicorn main:app --host 0.0.0.0 --port $PORT